### ISSUE TITLE
error in demo 

### ISSUE THREAD

**Issue by yi-xu** [roliveros-ramos/calibrar#2]
Hi, Ricardo
I've got an error when running the demo, I'm wondering if someone has the same problem or just myself?
**Error in { : task 1 failed - "The'yield'variable is NULL."**
Thanks!
Yi
> library(devtools)
> install_github("roliveros-ramos/calibrar")
Downloading GitHub repo roliveros-ramos/calibrar@master
√  checking for file 'C:\Users\HP\AppData\Local\Temp\RtmpOcPSpo\remotes6c984f691161\roliveros-ramos-calibrar-4d56e1d/DESCRIPTION' ...
-  preparing 'calibrar':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'calibrar_0.2.0.9002.tar.gz'
   
Installing package into ‘C:/Users/HP/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'calibrar' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'calibrar'
    finding HTML links ... done
    SphereN                                 html  
    calibrar-package                        html  
    calibrarDemo                            html  
    calibrate                               html  
    createObjectiveFunction                 html  
    getCalibrationInfo                      html  
    getObservedData                         html  
    optimES                                 html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (calibrar)
>  demo=osmose_calib_demo(path=NULL) #run successfully
>  setwd(demo$path)  #run successfully
>  source(demo$file)  #has the message
Loading required package: calibrar
Loading required package: doParallel
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel
Creating observed data list for calibration... 
Variable: TrachurusTrachurus.biomass

Variable: SardinaPilchardus.biomass

Variable: SardinellaAurita.biomass

Variable: EngraulisEncrasicolus.biomass

Variable: OctopusVulgaris.landings

Variable: MelicertusKerathurus.landings

Variable: MetapenaeusMonoceros.landings

Variable: TrachurusTrachurus.landings

Variable: SardinaPilchardus.landings

Variable: SardinellaAurita.landings

Variable: EngraulisEncrasicolus.landings

Variable: DiplodusAnnularis.landings

Variable: MustelusMustelus.landings

Variable: MerlucciusMerluccius.landings

Variable: PagellusErythrinus.landings

Variable: OctopusVulgaris.thr

Variable: MelicertusKerathurus.thr

Variable: MetapenaeusMonoceros.thr

Variable: TrachurusTrachurus.thr

Variable: SardinaPilchardus.thr

Variable: SardinellaAurita.thr

Variable: EngraulisEncrasicolus.thr

Variable: DiplodusAnnularis.thr

Variable: MustelusMustelus.thr

Variable: MerlucciusMerluccius.thr

Variable: PagellusErythrinus.thr

Optimizing 'popsize' to work with 2 cores.
Error in { : task 1 failed - "The'yield'variable is NULL."

**Comment by roliveros-ramos** [comment]
This issue is not related to calibrar, please check your installation or the source(demo$file) line.
