### ISSUE TITLE
Error when using CMAES

### ISSUE THREAD

**Issue by slehuta** [roliveros-ramos/calibrar#4]
while trying to launch calibrar using a different algorithm (CMA-ES), it does not create the ix sub-folders, but just i0 the first one (which is empty).
here is the error message

 > calib<- calibrate(par=rep(NA,11),fn=objfn, method='cmaes', lower=0,
upper=0.001, control=control)
Error in file(con, "r") : cannot open the connection
Calls: calibrate -> .calibrar -> .cmaes

**Comment by slehuta** [comment]
While running it locally on a dummy model and on ISIS-Fish I get the following error message : Error in arx[, aripop] : indice hors limites (="indices out of bounds"). The command to execute simulation "_i0" is printed 11 times (see below) (population's size is 12) but the simulations do not start.

command printed 11 times before error message appears :
-Xmx1024M -jar F:/ISIS-Fish/calibrISIS/isis-fish-4.4.2.5.jar --simulateWithSimulation testcmaes_i0 F:/ISIS-Fish/calibrISIS/zip_local.zip

**Comment by roliveros-ramos** [comment]
Please, update the calibrar package to the last version. Now you should get the following error:

```
Error in calibrate(par = rep(5e-05, 11), fn = objfn, method = "cmaes",  : 
  Method 'cmaes' does not support multi-objective optimization, use aggregate=TRUE in 'createObjectiveFunction'.
```
Re-run your code using aggregate=TRUE when creating the objective function.
