### ISSUE TITLE
CMAES does not run in parallel

### ISSUE THREAD

**Issue by slehuta** [roliveros-ramos/calibrar#5]
While calibrating using method CMA-ES, pop size = 12, nbcores = 6, maxgen = 3
- only one simulation is run at a time (no folder >i0 )
- the command for launching simulations is repeated 11 times (with name "_i0") although popsize is 12
- moreover although I limited to 3 generations it launched more and if I get it correctly plannes to realise 36 iterations (pop size x max gen)
- finally the fitness function is said to be flat which is weird (the model was previously calibrated and we know the function is responsive in these domain of values)

![cmaes_error](https://user-images.githubusercontent.com/57951611/69420845-d8c29700-0d1f-11ea-80fc-e4f0ceeddb6d.JPG)

**Comment by roliveros-ramos** [comment]
Sadly, the CMAES package does not provide explicit parallelization for cma_es(). I'd need to modify the function myself or contact the author. Other methods do provide parallelization, I will list them and include them in the help files, as well as a warning when parallel=TRUE is ignored.

**Comment by roliveros-ramos** [comment]
The last version of the package allows to read/write to the disk for all 19 methods currently implemented (so it always creates the appropiate i0, i1, ..., in folders needed to try different solutions). For clusters with schedulers like DATARMOR, the method 'Rvmmin' also has the restart functionality. This method uses derivatives, so can be used with deterministic models and in those cases should be way faster than AHR-ES, that was developed for stochastic models.  We are not planning anymore to modify the code of CMA-ES so it can be run in parallel, but many other methods do provide the functionality and are included in the package.
